version: '3.5'

services:
  influxdb:
    image: influxdb
    restart: always
    networks:
      - proxy-network
    ports:
      - 8086:8086
  gatewayapp:
    # dockerhub
    image: colinbut/githubcloudproxy:1.0.0
    restart: always
    networks:
      - proxy-network
    ports:
      - 8080:8080
    environment:
      KPI_DATABASE_URL: http://influxdb:8086
      KPI_DATABASE_USERNAME: root
      KPI_DATABASE_PASSWORD: root
networks:
  proxy-network:
    name: proxy-network